// sharedStyles.js

// Define common styles as object properties
export const sharedClasses = {
    bgZinc100: 'bg-zinc-100',
    bgWhite: 'bg-white',
    bgYellow400: 'bg-yellow-400',
    textZinc700: 'text-zinc-700',
    textZinc800: 'text-zinc-800',
    bgBlue500: 'bg-blue-500',
    bgBlue500TextWhite: 'bg-blue-500 text-white',
    container: 'container mx-auto px-4',
    flex: 'flex',
    justifyBetween: 'justify-between',
    itemsCenter: 'items-center',
    spaceX4: 'space-x-4',
    mt6: 'mt-6',
    p4: 'p-4',
    roundedLg: 'rounded-lg',
    textWhite: 'text-white',
    fontBold: 'font-bold',
    flexWrap: 'flex flex-wrap gap-4',
    wFull: 'w-full',
    mdW1_2: 'md:w-1/2',
    shadowMd: 'shadow-md',
    shadowLg: 'shadow-lg',
    fontSemibold: 'font-semibold',
    mb4: 'mb-4',
    flexItemsCenter: 'flex items-center',
    justifyBetweenPy2: 'justify-between py-2',
    borderB: 'border-b',
    mr4: 'mr-4',
    w8: 'w-8',
    h8: 'h-8',
    px4: 'px-4',
    py2: 'py-2',
    roundedFull: 'rounded-full',
    // Add more common styles as needed
};
